
###############################################################################
# @file Makefile
# @note HangZhou Hikvision Digital Technology Co., Ltd. All Right Reserved.
# @brief Top Makefile
# 
# @author   liuboyf1
# @data     2012-09-03
# @version  V1.0.0
###############################################################################

all : 
	cd dev;make
	cd app;make

clean :
	cd dev;make clean
	cd app;make clean

.PHONY : all clean
